### Listar o personagem
GET https://localhost:5001/api/personagem/listar

### Listar o User
GET https://localhost:5001/api/user/listar


### Cadastrar um Nivel
POST https://localhost:5001/api/nivel/cadastrar
Content-Type: application/json

{
    "fase" : "1",
    "boss" : "1"
}

### Listar o nivel
GET https://localhost:5001/api/nivel/listar

### Cadastrar um User
POST https://localhost:5001/api/user/cadastrar
Content-Type: application/json

{
    "nome" : "Eduardo",
    "email" : "asd@asd.com",
    "cpf" : "0123456789", 
    "senha" : "1000"
}

### Cadastrar um personagem
POST https://localhost:5001/api/personagem/cadastrar
Content-Type: application/json

{
    "nome" : "Edwards",
    "dano" : "2",
    "userid" : "1",
    "nivelid" : "1"
}



### Buscar um User pelo CPF
GET https://localhost:5001/api/user/buscar/0123456789

### Alterar um User
PATCH  https://localhost:5001/api/user/alterar
Content-Type: application/json

{
    "id" : 1,
    "nome" : "Diogo Steinke Deconto Modificado Teste",
    "email" : "asd@asd.com",
    "cpf" : "0123456789",
    "senha" : "1000",
    "Personagem" : 1

}

### Deletar um user pelo Id
DELETE https://localhost:5001/api/user/deletar/1

### Deletar um personagem pelo Id
DELETE https://localhost:5001/api/personagem/deletar/3

### Alterar um User
PATCH  https://localhost:5001/api/personagem/alterar
Content-Type: application/json

{
    "id" : "3",
    "nome" : "rodrigo",
    "dano" : "2",
    "userid" : "1",
    "nivelid" : "1"

}